"""Add metainfo column to Document table

Revision ID: da32b1f648a1
Revises: 6a9f914f656c
Create Date: 2025-06-27 14:07:22.734757

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da32b1f648a1'
down_revision = '6a9f914f656c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metainfo', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', models.types.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('conversation_id', models.types.StringUUID(), nullable=True))
        batch_op.add_column(sa.Column('file_key', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('original_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))

    with op.batch_alter_table('workflow_app_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('workflow_app_log_app_idx'))
        batch_op.create_index('workflow_app_log_app_idx', ['tenant_id', 'app_id', 'created_at'], unique=False)
        batch_op.create_index('workflow_app_log_workflow_run_idx', ['workflow_run_id'], unique=False)

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_app_id_idx'))
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_created_at_idx'))
        batch_op.create_index('workflow__conversation_variables_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('workflow__conversation_variables_created_at_idx', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow__conversation_variables_created_at_idx')
        batch_op.drop_index('workflow__conversation_variables_app_id_idx')
        batch_op.create_index(batch_op.f('workflow_conversation_variables_created_at_idx'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('workflow_conversation_variables_app_id_idx'), ['app_id'], unique=False)

    with op.batch_alter_table('workflow_app_logs', schema=None) as batch_op:
        batch_op.drop_index('workflow_app_log_workflow_run_idx')
        batch_op.drop_index('workflow_app_log_app_idx')
        batch_op.create_index(batch_op.f('workflow_app_log_app_idx'), ['tenant_id', 'app_id'], unique=False)

    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('name')
        batch_op.drop_column('original_url')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('file_key')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('metainfo')

    # ### end Alembic commands ###
